name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Each feature flag combination
        features:
          - ""
          - "stdlib"
          - "c_stdlib"
          - "stdlib c_stdlib"
          - "repl"
          - "c_stdlib repl"

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        if [ -z "${{ matrix.features }}" ]; then
          cargo test --verbose
        else
          cargo test --verbose --features "${{ matrix.features }}"
        fi
